name: Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize, review_requested]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workflow repository
        uses: actions/checkout@v2
        with:
          repository: Leuchtfeuer/mautic-ci-runner
          token: ${{ secrets.GH_TOKEN }}
          path: .github/ai_review
      - name: move action file
        run: mv .github/ai_review/.github/actions/ai_review ./github/pr_review
      - name: debug
        run: ls -la .github/pr_review
      - name: AI Code Review
        uses: ./.github/pr_review
        with:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}