name: Initialise Code Review
on:
  pull_request:
    types: [opened, reopened, synchronize, review_requested]

jobs:
  check_permissions:
    runs-on: ubuntu-latest
    name: Check permissions
    steps:
      - name: Permission granted
        if: contains('OWNER,MEMBER,COLLABORATOR', github.event.pull_request.author_association)
        run: echo "Permissions sufficient. Running Code Review"
      - name: Permission denied
        if: ${{ !contains('OWNER,MEMBER,COLLABORATOR', github.event.pull_request.author_association) }}
        run: echo "Permissions insufficient" && exit 1
